// lib/src/known_licenses_data.dart
// This file is generated by flutter_oss_manager. Do not modify.

const Map<String, String> knownLicensesData = {
  'Apache-2.0': r'''Apache License
Version 2.0, January 2004
http://www.apache.org/licenses/

TERMS AND CONDITIONS FOR USE, REPRODUCTION, AND DISTRIBUTION

1. Definitions.

"License" shall mean the terms and conditions for use, reproduction,
and distribution as defined by Sections 1 through 9 of this document.

"Licensor" shall mean the copyright owner or entity authorized by
the copyright owner that is granting the License.

"Legal Entity" shall mean the union of the acting entity and all
other entities that control, are controlled by, or are under common
control with that entity. For the purposes of this definition,
"control" means (i) the power, direct or indirect, to cause the
direction or management of such entity, whether by contract or
otherwise, or (ii) the ownership of fifty percent (50%) or more of
the outstanding shares, or (iii) beneficial ownership of such entity.

"You" (or "Your") shall mean an individual or Legal Entity
exercising permissions granted by this License.

"Source" form shall mean the preferred form for making modifications,
including but not limited to software source code, documentation
source, and configuration files.

"Object" form shall mean any form resulting from mechanical
transformation or translation of a Source form, including but
not limited to compiled object code, generated documentation,
and conversions to other media types.

"Work" shall mean the work of authorship, whether in Source or
Object form, made available under the License, as indicated by a
copyright notice that is included in or attached to the work
(an example is provided in the Appendix below).

"Derivative Works" shall mean any work, whether in Source or Object
form, that is based on (or derived from) the Work and for which the
editorial revisions, annotations, elaborations, or other modifications
represent, as a whole, an original work of authorship. For purposes
of this License, Derivative Works shall not include works that remain
separable from, or merely link (or bind by name) to the interfaces of,
the Work and Derivative Works thereof.

"Contribution" shall mean any work of authorship, including
the original version of the Work and any modifications or additions
to that Work or Derivative Works thereof, that is intentionally
submitted to Licensor for inclusion in the Work by the copyright owner
or by an individual or Legal Entity authorized to make submissions on
behalf of the copyright owner.

"Contributor" shall mean Licensor and any individual or Legal Entity
on behalf of whom a Contribution has been received by Licensor and
subsequently incorporated within the Work.

2. Grant of Copyright License.

Subject to the terms and conditions of this License, each Contributor
hereby grants to You a perpetual, worldwide, non-exclusive, no-charge,
royalty-free, irrevocable copyright license to reproduce, prepare
Derivative Works of, publicly display, publicly perform, sublicense,
and distribute the Work and such Derivative Works in Source or Object
form.

3. Grant of Patent License.

Subject to the terms and conditions of this License, each Contributor
hereby grants to You a perpetual, worldwide, non-exclusive, no-charge,
royalty-free, irrevocable (except as stated in this section) patent
license to make, have made, use, offer to sell, sell, import, and
otherwise transfer the Work, where such license applies only to those
patent claims licensable by such Contributor that are necessarily
infringed by their Contribution(s) alone or by combination of their
Contribution(s) with the Work to which such Contribution(s) was
submitted. If You institute patent litigation against any entity
(including a cross-claim or counterclaim in a lawsuit) alleging that the
Work or a Contribution incorporated within the Work constitutes direct
or contributory patent infringement, then any patent licenses granted to
You under this License for that Work shall terminate as of the date such
litigation is filed.

4. Redistribution.

You may reproduce and distribute copies of the Work or Derivative Works
thereof in any medium, with or without modifications, and in Source or
Object form, provided that You meet the following conditions:

(a) You must give any other recipients of the Work or Derivative Works
a copy of this License; and

(b) You must cause any modified files to carry prominent notices stating
that You changed the files; and

(c) You must retain, in the Source form of any Derivative Works that You
distribute, all copyright, patent, trademark, and attribution notices
from the Source form of the Work, excluding those notices that do not
pertain to any part of the Derivative Works; and

(d) If the Work includes a "NOTICE" text file as part of its
distribution, then any Derivative Works that You distribute must
include a readable copy of such NOTICE file, excluding those NOTICES
that do not pertain to any part of the Derivative Works, in at least
one of the following places: within a NOTICE text file distributed
as part of the Derivative Works; within the Source form or
documentation, if provided along with the Derivative Works; or, within
a display generated by the Derivative Works, if and wherever such
third-party notices normally appear. The contents of the NOTICE file
are for informational purposes only and do not modify the License.
You may add Your own attribution notices within Derivative Works that
You distribute, alongside or as an addendum to the NOTICE text from
the Work, provided that such additional attribution notices cannot be
construed as modifying the License.

You may add Your own copyright statement to Your modifications and may
provide additional or different license terms and conditions for use,
reproduction, or distribution of Your modifications, or for any such
Derivative Works as a whole, provided Your use, reproduction, and
distribution of the Work otherwise complies with the conditions stated
in this License.

5. Submission of Contributions.

Unless You explicitly state otherwise, any Contribution intentionally
submitted for inclusion in the Work by You to the Licensor shall be
under the terms and conditions of this License, without any additional
terms or conditions. Notwithstanding the above, nothing herein shall
supercede or modify the terms of any separate license agreement you
may have executed with Licensor regarding such Contributions.

6. Trademarks.

This License does not grant permission to use the trade names, trademarks,
service marks, or product names of the Licensor, except as required for
reasonable and customary use in describing the origin of the Work and
reproducing the content of the NOTICE file.

7. Disclaimer of Warranty.

Unless required by applicable law or agreed to in writing, Licensor provides
the Work (and each Contributor provides its Contributions) on an "AS IS"
BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or
implied, including, without limitation, any warranties or conditions
of TITLE, NON-INFRINGEMENT, MERCHANTABILITY, or FITNESS FOR A
PARTICULAR PURPOSE. You are solely responsible for determining the
appropriateness of using or redistributing the Work and assume any
risks associated with Your exercise of permissions under this License.

8. Limitation of Liability.

In no event and under no legal theory, whether in tort (including negligence),
contract, or otherwise, unless required by applicable law (such as deliberate
and grossly negligent acts) or agreed to in writing, shall any Contributor be
liable to You for damages, including any direct, indirect, special, incidental,
or consequential damages of any character arising as a result of this License
or out of the use or inability to use the Work (including but not limited to
damages for loss of goodwill, work stoppage, computer failure or malfunction,
or any and all other commercial damages or losses), even if such Contributor
has been advised of the possibility of such damages.

9. Accepting Warranty or Additional Liability.

While redistributing the Work or Derivative Works thereof, You may choose to
offer, and charge a fee for, acceptance of support, warranty, indemnity, or
other liability obligations and/or rights consistent with this License. However,
in accepting such obligations, You may act only on Your own behalf and on Your
sole responsibility, not on behalf of any other Contributor, and only if You
agree to indemnify, defend, and hold each Contributor harmless for any liability
incurred by, or claims asserted against, such Contributor by reason of your
accepting any such warranty or additional liability.

END OF TERMS AND CONDITIONS

APPENDIX: How to apply the Apache License to your work.

To apply the Apache License to your work, attach the following boilerplate notice
to the end of the copyright notice for your work. It is important to attach
this notice to the first part of your work to get the most benefit there from.

   Copyright [yyyy] [name of copyright owner]

   Licensed under the Apache License, Version 2.0 (the "License");
   you may not use this file except in compliance with the License.
   You may obtain a copy of the License at:

     http://www.apache.org/licenses/LICENSE-2.0

   Unless required by applicable law or agreed to in writing, software
   distributed under the License is distributed on an "AS IS" BASIS,
   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
   See the License for the specific language governing permissions and
   limitations under the License.
''',
  'BSD-2-Clause': r'''BSD 2-Clause "Simplified" License

Copyright (c) <year>, <owner>
All rights reserved.

Redistribution and use in source and binary forms, with or without
modification, are permitted provided that the following conditions are met:

1. Redistributions of source code must retain the above copyright notice,
   this list of conditions and the following disclaimer.

2. Redistributions in binary form must reproduce the above copyright notice,
   this list of conditions and the following disclaimer in the documentation
   and/or other materials provided with the distribution.

THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE
FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY,
OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
''',
  'BSD-3-Clause': r'''BSD 3-Clause New or Revised License

Copyright (c) <year>, <owner>
All rights reserved.

Redistribution and use in source and binary forms, with or without
modification, are permitted provided that the following conditions are met:

* Redistributions of source code must retain the above copyright notice, this
  list of conditions and the following disclaimer.

* Redistributions in binary form must reproduce the above copyright notice,
  this list of conditions and the following disclaimer in the documentation
  and/or other materials provided with the distribution.

* Neither the name of the copyright holder nor the names of its
  contributors may be used to endorse or promote products derived from
  this software without specific prior written permission.

THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE
FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY,
OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
''',
  'GPL-3.0': r'''GNU General Public License v3.0

Version 3, 29 June 2007

Copyright (C) 2007 Free Software Foundation, Inc. <https://fsf.org/>
Everyone is permitted to copy and distribute verbatim copies
of this license document, but changing it is not allowed.

Preamble

The GNU General Public License is a free, copyleft license for software and
other kinds of works.

The licenses for most software and other practical works are designed to take
away your freedom to share and change the works. By contrast, the GNU General
Public License is intended to guarantee your freedom to share and change all
versions of a program--to make sure it remains free software for all its users.
We, the Free Software Foundation, use the GNU General Public License for most
of our software; it applies also to any other work released this way by its
authors. You can use it too, for your programs.

When we speak of free software, we are referring to freedom, not price. Our
General Public Licenses are designed to make sure that you have the freedom to
distribute copies of free software (and charge for them if you wish), that you
receive source code or can get it if you want it, that you can change software
or use pieces of it in new free programs, and that you know you can do these
things.

To protect your rights, we need to prevent others from denying you these rights
or asking you to surrender the rights. Therefore, you have certain
responsibilities if you distribute copies of software, or if you modify it:
responsibilities to respect the freedom of others.

For example, if you distribute copies of such a program, whether gratis or for
a fee, you must pass on to the recipients the same freedoms that you received.
You must make sure that they, too, receive or can get the source code. And you
must show them these terms so they know their rights.

Developers that use the GNU GPL protect your rights with two steps: (1) by
asserting copyright on the software, and (2) offering you this License that
gives you legal permission to copy, distribute and/or modify it.

For the developers' and authors' protection, the GPL clearly explains that
there is no warranty for this free software. For both users' and developers'
sake, the GPL requires that modified versions be marked as such, so that their
problems will not be attributed to the authors' mistakes.

Some devices are designed to deny users access to install or run modified
versions of the software inside them, although the manufacturer can do so. This
is fundamentally incompatible with the aim of protecting users' freedom to
change the software. The systematic pattern of such abuse occurs in the area of
products for individuals to use, which is precisely where it is most
unacceptable. Therefore, we have designed this version of the GPL to prohibit
the practice for those products. If such problems arise in other sections of
the patent law, we stand ready to extend this provision to those sections to
protect the said freedom.

Finally, every program is threatened constantly by software patents. States
should not allow patents to restrict development and use of software. To avoid
that danger, the GPL ensures that patents cannot be used to render the program
non-free.

The precise terms and conditions for copying, distribution and modification
follow.

TERMS AND CONDITIONS

0. Definitions.

"This License" refers to version 3 of the GNU General Public License.

"Copyright" also means copyright-like laws that apply to other kinds of works,
such as semiconductor masks.

"The Program" refers to any copyrightable work licensed under this License.
Each licensee is addressed as "you". "Licensees" and "recipients" may be
individuals or organizations.

To "modify" a work means to copy from or adapt all or part of the work in a
fashion requiring copyright permission, other than the making of an exact copy.
The resulting work is called a "modified version" of the earlier work or a work
"based on" the earlier work.

A "covered work" means either the unmodified Program or a work based on the
Program.

To "propagate" a work means to do anything with it that, without permission
from copyright, would make you directly or secondarily liable for infringement
under applicable copyright law, except executing it on a computer or modifying
a private copy. Propagation includes copying, redistribution (with or without
modification), linking, compiling, and reverse engineering, and more.

A "contributed work" is the Program, or any work based on the Program, which
is made available to the public by a Contributor.

A "Contributor" is an author or other copyright holder who authorizes use under
this License of the Program or a work on which the Program is based.

"The Corresponding Source" for a work in object code form means all the source
code needed to generate, install, and (for an executable work) run the object
code and to modify the work, including scripts to control those activities.
However, it does not include the work's System Libraries, or general-purpose
tools or generally available free programs which are used unmodified in
performing those activities but which are not part of the work.

For example, Corresponding Source includes interface definition files associated
with source files for the work, and the source code for shared libraries and
dynamically linked subprograms that the work is specifically designed to require,
such as by intimate data communication or control flow between those subprograms
and other parts of the work.

The Corresponding Source need not include anything that users can regenerate
automatically from other parts of the Corresponding Source.

The Corresponding Source for a work in module form need not include the source
code for the module itself, if the module is a System Library.

"System Libraries" are those that are part of the Program's normal operating
environment, but are not part of the Program itself. This does not limit the
scope of the Program, but only serves to clarify that the Program is not
required to include source code for such libraries.

A "User Product" is either (1) a "consumer product", which means a tangible
personal property which is normally used for personal, family, or household
purposes, or (2) anything designed or sold for incorporation into a consumer
product. In determining whether a product is a consumer product, doubtful cases
shall be resolved in favor of coverage. For a particular product, "normally used"
means a typical or common use of that class of product, regardless of the number
of users or the way in which the particular product is actually used. Thus, a
product is a consumer product if it has substantial functionality normally used
in a consumer product, even if it is marketed to manufacturers of industrial
products.

A "Installation Information" for a User Product means any methods, procedures,
authorization keys, or other information required to install and execute
modified versions of a covered work in that User Product from a modified version
of its Corresponding Source. The information must suffice to ensure that the
continued functioning of the modified object code is in no case prevented or
interfered with merely because modification has been made.

"Legal Notice" is any notice that announces that a work is published under
this License.

1. Source Code.

The Corresponding Source for a covered work in object code form must be conveyed
in an object code form that is machine-readable and is accompanied by a copy of
this License. The Corresponding Source must be conveyed in a source code form
that is machine-readable and is accompanied by a copy of this License.

2. Basic Permissions.

All rights granted under this License are granted for the term of copyright on
the Program, and are irrevocable provided the stated conditions are met. This
License explicitly affirms your unlimited permission to run the unmodified
Program. The output from running a covered work is covered by this License only
if the output, with its output, constitutes a covered work.

3. Protecting Users' Legal Rights From Anti-Circumvention Law.

No covered work shall be deemed part of an effective technological measure under
any applicable law fulfilling obligations under article 11 of the WIPO copyright
treaty adopted on 20 December 1996, or similar laws prohibiting or restricting
circumvention of technological measures.

4. Conveying Verbatim Copies.

You may convey verbatim copies of the Program's source code as you receive it,
in any medium, provided that you conspicuously and appropriately publish on each
copy an appropriate copyright notice; keep intact all notices stating that this
License and any non-permissive terms added in accord with section 7 apply to the
code; keep intact all notices of the absence of any warranty; and give all
recipients a copy of this License along with the Program.

You may charge any price or no price for each copy that you convey, and you may
offer support or warranty protection for a fee.

5. Conveying Modified Source Versions.

You may convey a work based on the Program, or the modifications to produce it
from the Program, in the form of source code under the terms of section 4,
provided that you also meet all of these conditions:

a) The work must carry prominent notices stating that you modified it, and giving
a relevant date.

b) The work must carry prominent notices stating that it is released under this
License and any conditions added under section 7. This requirement modifies the
requirement in section 4 to "keep intact all notices".

c) You must license the entire work, as a whole, under this License to anyone
who comes into possession of a copy. This License will therefore apply, along
with any applicable section 7 additional terms, to the whole of the work, and
all its parts, regardless of how they are packaged. This License gives no
permission to license the work in any other way, but it does not invalidate such
permission if you have received it separately.

d) If the work has interactive user interfaces, each must display an
"Appropriate Legal Notices" notice; but if the Program has interactive
interfaces that do not display an "Appropriate Legal Notices" notice, your
work need not make them do so.

A compilation of a covered work with other separate and independent works, which
are not by their nature extensions of the covered work, and which are not
combined with it such as to form a larger program, in or on a volume of a storage
or distribution medium, is called an "aggregate". The aggregate does not have
to have a license applied to it by this License. However, if you include a
covered work in an aggregate, the covered work continues to be governed by this
License.

6. Conveying Non-Source Forms.

You may convey a covered work in object code form under the terms of sections 4
and 5, provided that you also meet all of these conditions:

a) Convey the object code in, or embodied in, a physical product (including a
physical distribution medium), or in a medium customarily used for public
interchange, or in a medium customarily used for software interchange.

b) Convey all the Corresponding Source for a covered work in object code form
under the terms of this License, in one of the ways specified in section 4.

c) Convey the Installation Information, if any, in a way that gives users access
to install and execute modified versions of the covered work in the User Product
from a modified version of its Corresponding Source. The information must
suffice to ensure that the continued functioning of the modified object code is
in no case prevented or interfered with merely because modification has been made.

7. Additional Terms.

"Additional permissions" are terms that supplement the terms of this License by
making exceptions from one or more of its conditions. Additional permissions
that are applicable to the entire Program shall be treated as though they were
included in this License, to the extent that they are valid under applicable law.
If additional permissions apply only to part of the Program, that part may be
used separately under those permissions, provided the rest of the Program is
used under this License. Nothing in this License grants permission to run the
Program in any other way.

When you convey a copy of a covered work, you may at your option remove any
additional permissions from that copy, or from any part of it. (Additional
permissions may be written to require their own removal in certain cases when
you modify the work.) You may place additional permissions on material, added by
you to a covered work, for which you have or can give appropriate copyright
permission.

Notwithstanding any other provision of this License, for material you add to a
covered work, you may (if authorized by the copyright holders of that material)
supplement the terms of this License with terms:

a) Disclaiming warranty or limiting liability differently from the terms of
sections 15 and 16 of this License; or

b) Requiring preservation of specified legal notices or author attributions in
that material or in the Appropriate Legal Notices displayed by works containing
the material; or

c) Prohibiting misrepresentation of the origin of that material, or requiring
that modified versions of such material be marked in reasonable ways as differing
from the original version; or

d) Limiting the use for publicity purposes of names or trademarks of the
authors or licensors of the material; or

e) Requiring indemnification of licensors and authors of that material by anyone
who conveys the material (or modified versions of it) with contractual assumptions
of liability to the recipient, for any liability that the contractual assumptions
of liability entail.

All other non-permissive additional terms are considered "further restrictions"
within the meaning of section 10. If the Program as you received it, or any
covered work to which you convey it, contains such further restrictions, you must
remove those restrictions before conveying it. You may not convey a covered work
if you are a party to an arrangement that deals with the distribution of the
software, under which you make payment to the third party for the exercise of the
right to convey the software, and under which the third party grants, to any party
who receives the software, a discriminatory patent license (a) in connection with
copies of the software conveyed by you (b) under patent claims that are infringed
by the software, combined with the software, or by the software's use.

8. Termination.

You may not propagate or modify a covered work except as expressly provided under
this License. Any attempt otherwise to propagate or modify it is void, and will
automatically terminate your rights under this License (including any patent
licenses granted under the second paragraph of section 11).

However, if you cease all violation of this License, then your license from a
particular copyright holder is reinstated (a) provisionally, unless and until the
copyright holder explicitly and finally terminates your license, and (b) permanently,
if the copyright holder fails to notify you of the violation by any reasonable
means prior to 60 days after the cessation.

Moreover, your license from a particular copyright holder is reinstated permanently
if the copyright holder notifies you of the violation by some reasonable means, this
is the first time you have received notice of violation of this License (for any
work) from that copyright holder, and you cure the violation prior to 30 days after
your receipt of the notice.

Termination of your rights under this section does not terminate the patent licenses
of parties who have received copies or rights from you under this License. If a
work is terminated and ceases to be a covered work, in whole or in part, the
parties who have received copies of that work from you under this License will not
have their licenses terminated so long as they remain in full compliance. However,
nothing in this section purports to revoke or alter any other permissions that may
be had of the work.

9. Acceptance Not Required for Having Copies.

You are not required to accept this License in order to receive or run a copy of
the Program. Ancillary propagation of a covered work occurring solely as a
consequence of using peer-to-peer transmission to receive a copy likewise does not
require acceptance. However, nothing in this License grants you permission to
propagate or modify any covered work. These actions infringe copyright if you do
not accept this License. Therefore, by modifying or propagating a covered work,
you indicate your acceptance of this License to do so.

10. Automatic Licensing of Downstream Recipients.

Each time you convey a covered work, the recipient automatically receives a license
from the original licensors, to run, modify, and propagate that work, subject to
this License. You are not responsible for enforcing compliance by third parties
with this License.

11. Patents.

A "contributor version" is a work that has been contributed to the Program.

Subject to the terms and conditions of this License, each contributor grants to
you a non-exclusive, worldwide, royalty-free patent license to make, use, sell,
offer for sale, import, and otherwise transfer the contributor version, where
such license applies only to those patent claims licensable by such contributor
that are necessarily infringed by their contributor version alone or by
combination of their contributor version with the Program (or a work based on
the Program) to which the contributor version was contributed.

If you institute patent litigation against any entity (including a cross-claim or
counterclaim in a lawsuit) alleging that a contributor version is infringing patent
claims, then any patent licenses granted to you by that contributor under this
License for that contributor version automatically terminate.

A patent license is also terminated if you are a party to an arrangement that
deals with the distribution of the software, under which you make payment to the
third party for the exercise of the right to convey the software, and under which
the third party grants, to any party who receives the software, a discriminatory
patent license (a) in connection with copies of the software conveyed by you (b)
under patent claims that are infringed by the software, combined with the software,
or by the software's use.

12. No Surrender of Others' Freedom.

If conditions are imposed on you (whether by court order, agreement or otherwise)
that contradict the conditions of this License, they do not excuse you from the
conditions of this License. If you cannot convey a covered work so as to satisfy
simultaneously your obligations under this License and any other pertinent
obligations, then as a consequence you may not convey it at all. For example, if
you agree to terms that obligate you to collect a royalty for onward propagation
of the Program, and the only way you could satisfy that term is to violate this
License, then you must not propagate the Program.

13. Use with the GNU Affero General Public License.

Notwithstanding any other provision of this License, you have permission to link
or combine any covered work with a work licensed under version 3 of the GNU Affero
General Public License into a single combined work, and to convey the resulting
work. The terms of this License will continue to apply to the part which is the
covered work, but the special requirements of the GNU Affero General Public License
will apply to the combined work as a whole.

14. Revised Versions of this License.

The Free Software Foundation may publish revised and/or new versions of the GNU
General Public License from time to time. Such new versions will be similar in
spirit to the present version, but may differ in detail to address new problems
or concerns.

Each version is given a distinguishing version number. If the Program specifies
that a certain numbered version of the GNU General Public License "or any later
version" applies to it, you have the option of following the terms and conditions
either of that numbered version or of any later version published by the Free
Software Foundation. If the Program does not specify a version number of the GNU
General Public License, you may choose any version ever published by the Free
Software Foundation.

15. Disclaimer of Warranty.

THERE IS NO WARRANTY FOR THE PROGRAM, TO THE EXTENT PERMITTED BY APPLICABLE LAW.
EXCEPT WHEN OTHERWISE STATED IN WRITING THE COPYRIGHT HOLDERS AND/OR OTHER PARTIES
PROVIDE THE PROGRAM "AS IS" WITHOUT WARRANTY OF ANY KIND, EITHER EXPRESSED OR
IMPLIED, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY
AND FITNESS FOR A PARTICULAR PURPOSE. THE ENTIRE RISK AS TO THE QUALITY AND
PERFORMANCE OF THE PROGRAM IS WITH YOU. SHOULD THE PROGRAM PROVE DEFECTIVE, YOU
ASSUME THE COST OF ALL NECESSARY SERVICING, REPAIR OR CORRECTION.

16. Limitation of Liability.

IN NO EVENT UNLESS REQUIRED BY APPLICABLE LAW OR AGREED TO IN WRITING WILL ANY
COPYRIGHT HOLDER, OR ANY OTHER PARTY WHO MODIFIES AND/OR CONVEYS THE PROGRAM AS
PERMITTED ABOVE, BE LIABLE TO YOU FOR DAMAGES, INCLUDING ANY GENERAL, SPECIAL,
INCIDENTAL OR CONSEQUENTIAL DAMAGES ARISING OUT OF THE USE OR INABILITY TO USE
THE PROGRAM (INCLUDING BUT NOT LIMITED TO LOSS OF DATA OR DATA BEING RENDERED
INACCURATE OR LOSSES SUSTAINED BY YOU OR THIRD PARTIES OR A FAILURE OF THE PROGRAM
TO OPERATE WITH ANY OTHER PROGRAMS), EVEN IF SUCH HOLDER OR OTHER PARTY HAS BEEN
ADVISED OF THE POSSIBILITY OF SUCH DAMAGES.

17. Interpretation of Sections 15 and 16.

If the disclaimer of warranty and limitation of liability provided above cannot be
given local legal effect according to their terms, reviewing courts shall apply
local law that most closely approximates an absolute waiver of all civil liability
in connection with the Program, unless a warranty or assumption of liability accompanies
a copy of the Program in return for a fee.

END OF TERMS AND CONDITIONS

How to Apply These Terms to Your New Programs

If you develop a new program, and you want it to be of the greatest possible use to
the public, the best way to achieve this is to make it free software which everyone
can redistribute and change under these terms.

To do so, attach the following notices to the program.
It is safest to attach them to the start of every source file
to most effectively state the exclusion of warranty; and each file
should have at least the "copyright" line and a pointer to where the full notice is located.

    <one line to give the program's name and a brief idea of what it does.>
    Copyright (C) <year>  <name of author>

    This program is free software: you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.

    This program is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with this program.  If not, see <https://www.gnu.org/licenses/>.

Also add information on how to contact you by electronic and paper mail.

If the program does not do interactive graphics but runs in a text mode, it is
a good idea to print a notice like this:

  <program>  Copyright (C) <year>  <name of author>

  This program comes with ABSOLUTELY NO WARRANTY; for details type `show w'.
  This is free software, and you are welcome to redistribute it
  under certain conditions; type `show c' for details.

If you have GNU Emacs, it's a good idea to install the `dir' command and then
use `M-x add-file-local-variable' to add `mode: doc; fill-column: 75;' to the
file.

For information on why the GNU Lesser General Public License and GNU Affero
General Public License are sometimes better than the GNU General Public License,
see the separate explanation at <https://www.gnu.org/licenses/lgpl-howto.html>.
''',
  'ISC': r'''ISC License

Copyright (c) <year> <owner>

Permission to use, copy, modify, and/or distribute this software for any
purpose with or without fee is hereby granted, provided that the above
copyright notice and this permission notice appear in all copies.

THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES
WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF
MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN
ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF
OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.
''',
  'LGPL-3.0': r'''GNU Lesser General Public License v3.0

Version 3, 29 June 2007

Copyright (C) 2007 Free Software Foundation, Inc. <https://fsf.org/>
Everyone is permitted to copy and distribute verbatim copies
of this license document, but changing it is not allowed.

This version of the GNU Lesser General Public License incorporates the terms and
conditions of version 3 of the GNU General Public License, supplemented by the
additional permissions listed below.

0. Additional Definitions.

As used herein, "this License" refers to version 3 of the GNU Lesser General
Public License, and the "GNU GPL" refers to version 3 of the GNU General Public
License.

"The Library" refers to a covered work governed by this License, other than an
Executable Program as defined below.

An "Executable Program" is any work produced by compiling or interpreting a
covered work that is not a Library, in such a way that it requires the Library
to be present for execution.

"A Combined Work" is a work produced by combining or linking an instance of the
Library with an Executable Program. The particular terms of the GNU GPL that
apply to the Combined Work are those that apply to the Executable Program.

"Minimal Corresponding Source" for a Combined Work means the Corresponding Source
for the Executable Program, excluding any source code for the Library.

"Corresponding Application Binary" for a Combined Work means the object code and
executable form of the Executable Program, including any data and utility programs
needed for its execution, but excluding the Library.

1. Exception to Section 3 of the GNU GPL.

You may convey a covered work under sections 3 and 4 of this License without
being bound by section 3 of the GNU GPL.

2. Conveying Modified Versions.

If you modify a copy of the Library, and you convey it as a modified work, you
must fulfill all the obligations of the GNU GPL, including section 4, for the
modified version of the Library, and you must also do the following:

a) The modified work must carry prominent notices stating that you modified it,
and giving a relevant date.

b) The modified work must carry prominent notices stating that it is released
under this License and any conditions added under section 7. This requirement
modifies the requirement in section 4 to "keep intact all notices".

c) You must license the entire work, as a whole, under this License to anyone
who comes into possession of a copy. This License will therefore apply, along
with any applicable section 7 additional terms, to the whole of the work, and
all its parts, regardless of how they are packaged. This License gives no
permission to license the work in any other way, but it does not invalidate such
permission if you have received it separately.

d) If the work has interactive user interfaces, each must display an
"Appropriate Legal Notices" notice; but if the Program has interactive
interfaces that do not display an "Appropriate Legal Notices" notice, your
work need not make them do so.

A compilation of a covered work with other separate and independent works, which
are not by their nature extensions of the covered work, and which are not
combined with it such as to form a larger program, in or on a volume of a storage
or distribution medium, is called an "aggregate". The aggregate does not have
to have a license applied to it by this License. However, if you include a
covered work in an aggregate, the covered work continues to be governed by this
License.

3. Conveying Non-Source Forms.

You may convey a covered work in object code form under the terms of sections 4
and 5, provided that you also meet all of these conditions:

a) Convey the object code in, or embodied in, a physical product (including a
physical distribution medium), or in a medium customarily used for public
interchange, or in a medium customarily used for software interchange.

b) Convey all the Corresponding Source for a covered work in object code form
under the terms of this License, in one of the ways specified in section 4.

c) Convey the Installation Information, if any, in a way that gives users access
to install and execute modified versions of the covered work in the User Product
from a modified version of its Corresponding Source. The information must
suffice to ensure that the continued functioning of the modified object code is
in no case prevented or interfered with merely because modification has been made.

4. Additional Terms.

"Additional permissions" are terms that supplement the terms of this License by
making exceptions from one or more of its conditions. Additional permissions
that are applicable to the entire Program shall be treated as though they were
included in this License, to the extent that they are valid under applicable law.
If additional permissions apply only to part of the Program, that part may be
used separately under those permissions, provided the rest of the Program is
used under this License. Nothing in this License grants permission to run the
Program in any other way.

When you convey a copy of a covered work, you may at your option remove any
additional permissions from that copy, or from any part of it. (Additional
permissions may be written to require their own removal in certain cases when
you modify the work.) You may place additional permissions on material, added by
you to a covered work, for which you have or can give appropriate copyright
permission.

Notwithstanding any other provision of this License, for material you add to a
covered work, you may (if authorized by the copyright holders of that material)
supplement the terms of this License with terms:

a) Disclaiming warranty or limiting liability differently from the terms of
sections 15 and 16 of this License; or

b) Requiring preservation of specified legal notices or author attributions in
that material or in the Appropriate Legal Notices displayed by works containing
the material; or

c) Prohibiting misrepresentation of the origin of that material, or requiring
that modified versions of such material be marked in reasonable ways as differing
from the original version; or

d) Limiting the use for publicity purposes of names or trademarks of the
authors or licensors of the material; or

e) Requiring indemnification of licensors and authors of that material by anyone
who conveys the material (or modified versions of it) with contractual assumptions
of liability to the recipient, for any liability that the contractual assumptions
of liability entail.

All other non-permissive additional terms are considered "further restrictions"
within the meaning of section 10. If the Program as you received it, or any
covered work to which you convey it, contains such further restrictions, you must
remove those restrictions before conveying it. You may not convey a covered work
if you are a party to an arrangement that deals with the distribution of the
software, under which you make payment to the third party for the exercise of the
right to convey the software, and under which the third party grants, to any party
who receives the software, a discriminatory patent license (a) in connection with
copies of the software conveyed by you (b) under patent claims that are infringed
by the software, combined with the software, or by the software's use.

5. Termination.

You may not propagate or modify a covered work except as expressly provided under
this License. Any attempt otherwise to propagate or modify it is void, and will
automatically terminate your rights under this License (including any patent
licenses granted under the second paragraph of section 11).

However, if you cease all violation of this License, then your license from a
particular copyright holder is reinstated (a) provisionally, unless and until the
copyright holder explicitly and finally terminates your license, and (b) permanently,
if the copyright holder fails to notify you of the violation by any reasonable
means prior to 60 days after the cessation.

Moreover, your license from a particular copyright holder is reinstated permanently
if the copyright holder notifies you of the violation by some reasonable means, this
is the first time you have received notice of violation of this License (for any
work) from that copyright holder, and you cure the violation prior to 30 days after
your receipt of the notice.

Termination of your rights under this section does not terminate the patent licenses
of parties who have received copies or rights from you under this License. If a
work is terminated and ceases to be a covered work, in whole or in part, the
parties who have received copies of that work from you under this License will not
have their licenses terminated so long as they remain in full compliance. However,
nothing in this section purports to revoke or alter any other permissions that may
be had of the work.

6. Acceptance Not Required for Having Copies.

You are not required to accept this License in order to receive or run a copy of
the Program. Ancillary propagation of a covered work occurring solely as a
consequence of using peer-to-peer transmission to receive a copy likewise does not
require acceptance. However, nothing in this License grants you permission to
propagate or modify any covered work. These actions infringe copyright if you do
not accept this License. Therefore, by modifying or propagating a covered work,
you indicate your acceptance of this License to do so.

7. Automatic Licensing of Downstream Recipients.

Each time you convey a covered work, the recipient automatically receives a license
from the original licensors, to run, modify, and propagate that work, subject to
this License. You are not responsible for enforcing compliance by third parties
with this License.

8. Patents.

A "contributor version" is a work that has been contributed to the Program.

Subject to the terms and conditions of this License, each contributor grants to
you a non-exclusive, worldwide, royalty-free patent license to make, use, sell,
offer for sale, import, and otherwise transfer the contributor version, where
such license applies only to those patent claims licensable by such contributor
that are necessarily infringed by their contributor version alone or by
combination of their contributor version with the Program (or a work based on
the Program) to which the contributor version was contributed.

If you institute patent litigation against any entity (including a cross-claim or
counterclaim in a lawsuit) alleging that a contributor version is infringing patent
claims, then any patent licenses granted to you by that contributor under this
License for that contributor version automatically terminate.

A patent license is also terminated if you are a party to an arrangement that
deals with the distribution of the software, under which you make payment to the
third party for the exercise of the right to convey the software, and under which
the third party grants, to any party who receives the software, a discriminatory
patent license (a) in connection with copies of the software conveyed by you (b)
under patent claims that are infringed by the software, combined with the software,
or by the software's use.

9. No Surrender of Others' Freedom.

If conditions are imposed on you (whether by court order, agreement or otherwise)
that contradict the conditions of this License, they do not excuse you from the
conditions of this License. If you cannot convey a covered work so as to satisfy
simultaneously your obligations under this License and any other pertinent
obligations, then as a consequence you may not convey it at all. For example, if
you agree to terms that obligate you to collect a royalty for onward propagation
of the Program, and the only way you could satisfy that term is to violate this
License, then you must not propagate the Program.

10. Use with the GNU Affero General Public License.

Notwithstanding any other provision of this License, you have permission to link
or combine any covered work with a work licensed under version 3 of the GNU Affero
General Public License into a single combined work, and to convey the resulting
work. The terms of this License will continue to apply to the part which is the
covered work, but the special requirements of the GNU Affero General Public License
will apply to the combined work as a whole.

11. Revised Versions of this License.

The Free Software Foundation may publish revised and/or new versions of the GNU
Lesser General Public License from time to time. Such new versions will be similar
in spirit to the present version, but may may differ in detail to address new problems
or concerns.

Each version is given a distinguishing version number. If the Program specifies
that a certain numbered version of the GNU Lesser General Public License "or any
later version" applies to it, you have the option of following the terms and
conditions either of that numbered version or of any later version published by
the Free Software Foundation. If the Program does not specify a version number of
the GNU Lesser General Public License, you may choose any version ever published
by the Free Software Foundation.

12. Disclaimer of Warranty.

THERE IS NO WARRANTY FOR THE PROGRAM, TO THE EXTENT PERMITTED BY APPLICABLE LAW.
EXCEPT WHEN OTHERWISE STATED IN WRITING THE COPYRIGHT HOLDERS AND/OR OTHER PARTIES
PROVIDE THE PROGRAM "AS IS" WITHOUT WARRANTY OF ANY KIND, EITHER EXPRESSED OR
IMPLIED, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY
AND FITNESS FOR A PARTICULAR PURPOSE. THE ENTIRE RISK AS TO THE QUALITY AND
PERFORMANCE OF THE PROGRAM IS WITH YOU. SHOULD THE PROGRAM PROVE DEFECTIVE, YOU
ASSUME THE COST OF ALL NECESSARY SERVICING, REPAIR OR CORRECTION.

13. Limitation of Liability.

IN NO EVENT UNLESS REQUIRED BY APPLICABLE LAW OR AGREED TO IN WRITING WILL ANY
COPYRIGHT HOLDER, OR ANY OTHER PARTY WHO MODIFIES AND/OR CONVEYS THE PROGRAM AS
PERMITTED ABOVE, BE LIABLE TO YOU FOR DAMAGES, INCLUDING ANY GENERAL, SPECIAL,
INCIDENTAL OR CONSEQUENTIAL DAMAGES ARISING OUT OF THE USE OR INABILITY TO USE
THE PROGRAM (INCLUDING BUT NOT LIMITED TO LOSS OF DATA OR DATA BEING RENDERED
INACCURATE OR LOSSES SUSTAINED BY YOU OR THIRD PARTIES OR A FAILURE OF THE PROGRAM
TO OPERATE WITH ANY OTHER PROGRAMS), EVEN IF SUCH HOLDER OR OTHER PARTY HAS BEEN
ADVISED OF THE POSSIBILITY OF SUCH DAMAGES.

14. Interpretation of Sections 15 and 16.

If the disclaimer of warranty and limitation of liability provided above cannot be
given local legal effect according to their terms, reviewing courts shall apply
local law that most closely approximates an absolute waiver of all civil liability
in connection with the Program, unless a warranty or assumption of liability accompanies
a copy of the Program in return for a fee.

END OF TERMS AND CONDITIONS

How to Apply These Terms to Your New Programs

If you develop a new program, and you want it to be of the greatest possible use to
the public, the best way to achieve this is to make it free software which everyone
can redistribute and change under these terms.

To do so, attach the following notices to the program.
It is safest to attach them to the start of every source file
to most effectively state the exclusion of warranty; and each file
should have at least the "copyright" line and a pointer to where the full notice is located.

    <one line to give the program's name and a brief idea of what it does.>
    Copyright (C) <year>  <name of author>

    This program is free software: you can redistribute it and/or modify
    it under the terms of the GNU Lesser General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.

    This program is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU Lesser General Public License for more details.

    You should have received a copy of the GNU Lesser General Public License
    along with this program.  If not, see <https://www.gnu.org/licenses/>.

Also add information on how to contact you by electronic and paper mail.

If the program does not do interactive graphics but runs in a text mode, it is
a good idea to print a notice like this:

  <program>  Copyright (C) <year>  <name of author>

  This program comes with ABSOLUTELY NO WARRANTY; for details type `show w'.
  This is free software, and you are welcome to redistribute it
  under certain conditions; type `show c' for details.

If you have GNU Emacs, it's a good idea to install the `dir' command and then
use `M-x add-file-local-variable' to add `mode: doc; fill-column: 75;' to the
file.

For information on why the GNU Lesser General Public License and GNU Affero
General Public License are sometimes better than the GNU General Public License,
see the separate explanation at <https://www.gnu.org/licenses/lgpl-howto.html>.
''',
  'MIT': r'''MIT License

Copyright (c) [year] [fullname]

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES
WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF
MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN
ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF
OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.
''',
  'MPL-2.0': r'''Mozilla Public License 2.0

1. Definitions

1.1. “Contributor”
    means each individual or legal entity that creates, contributes to the
    creation of, or owns Covered Software.

1.2. “Contributor Version”
    means Covered Software of a Contributor, in Source Code form, plus the
    Contributor’s Modifications.

1.3. “Covered Software”
    means Source Code Form to which the initial Contributor has attached the
    notice in Exhibit A, and any Modifications of that Source Code Form.

1.4. “Executable Form”
    means any form of Covered Software other than Source Code Form.

1.5. “Initial Developer”
    means the individual or legal entity that first makes, or causes to be
    made, Covered Software available under this License.

1.6. “Larger Work”
    means a work that combines Covered Software with other material, some of
    which is not Covered Software.

1.7. “License”
    means this document.

1.8. “Licensable”
    means having the right to grant, to the maximum extent possible, whether
    at the time of the initial grant or subsequently, any and all of the
    rights conveyed by this License.

1.9. “Modifications”
    means any of the following:

    a. Any addition to or deletion from the substance or structure of either
       Source Code Form or Executable Form of the Covered Software.
    b. Any new Source Code Form or Executable Form, that contains any part of
       the Covered Software.

1.10. “Patent Claims” of a Contributor
    means any patent claim(s), including without limitation, method, process,
    and apparatus claims, in any patent Licensable by that Contributor that
    is necessarily infringed by the use or sale of its Contributor Version
    alone or in combination with the Covered Software as distributed by the
    Initial Developer.

1.11. “Source Code Form”
    means the form of the Covered Software preferred for making modifications
    to it, including but not limited to source code, documentation source,
    and configuration files.

1.12. “You” (or “Your”)
    means an individual or a legal entity exercising rights under this License.
    For legal entities, “You” includes any entity that controls, is controlled
    by, or is under common control with You. For purposes of this definition,
    “control” means (a) the power, direct or indirect, to cause the direction
    or management of such entity, whether by contract or otherwise, or (b)
    ownership of fifty percent (50%) or more of the outstanding shares or (c)
    beneficial ownership of such entity.

2. License Grants and Conditions

2.1. Grants

Each Contributor hereby grants You a world-wide, royalty-free, non-exclusive
license:

a. under intellectual property rights (other than patent or trademark) Licensable
   by that Contributor, to use, reproduce, make available, modify, display,
   perform, distribute, and otherwise exploit its Contributor Version as Covered
   Software, or as a component of a Larger Work; and

b. under Patent Claims of that Contributor, to make, use, sell, offer for sale,
   import, and otherwise transfer the Contributor Version.

2.2. Availability of Source Code

The Covered Software must be made available in Source Code Form. Your right to
create and distribute Executable Forms of the Covered Software is conditioned upon
Your compliance with the requirements of Section 3.1.

2.3. Limitations on Grant of Rights

Sections 2.1(a) and 2.1(b) do not, expressly or impliedly, grant any right or
license under any patent claim(s) of any Contributor, other than those Patent
Claims Licensable by that Contributor that are necessarily infringed by its
Contributor Version alone or in combination with the Covered Software as
distributed by the Initial Developer.

3. Distribution Obligations

3.1. Availability of Source Code

Any Covered Software that You distribute or otherwise make available in Executable
Form must also be made available in Source Code Form and covered by the terms of
this License. You must inform recipients of the Executable Form as to how they can
obtain a copy of the Source Code Form.

3.2. Modifications

Your Modifications, and any other Covered Software that You distribute or otherwise
make available, must be licensed under the terms of this License. You must include a
copy of this License with every copy of the Source Code Form of Covered Software You
distribute or otherwise make available. You must inform recipients of the Executable
Form as to how they can obtain a copy of the Source Code Form.

3.3. Larger Works

You may create a Larger Work by combining Covered Software with other material, provided
that You comply with the terms of this License for the Covered Software. You may opt to
apply a different license to the other material in the Larger Work.

3.4. Patent Claims

If You distribute or otherwise make available Covered Software, You agree to provide
recipients with a royalty-free, non-exclusive license under any Patent Claims of Yours
that are necessarily infringed by the Covered Software. The grant of this Section 3.4
applies only to the Covered Software as distributed by the Initial Developer.

3.5. Additional Terms

You may choose to offer, and charge a fee for, acceptance of support, warranty,
indemnity or other liability obligations and/or rights consistent with this License.
However, in accepting such obligations, You may act only on Your own behalf and on Your
sole responsibility, not on behalf of any other Contributor, and only if You agree to
indemnify, defend, and hold each Contributor harmless for any liability incurred by, or
claims asserted against, such Contributor by reason of your accepting any such warranty
or additional liability.

4. Versions of the License

4.1. New Versions

Mozilla Foundation is the license steward. Except as provided in Section 4.3, no one
other than the Mozilla Foundation may modify or publish new versions of this License.
Each version will be given a distinguishing version number.

4.2. Effect of New Versions

You may use the Covered Software under the terms of the version of the License under which
the Covered Software was received, or under the terms of any subsequent version published
by the license steward. If a Contributor Version provides that the Covered Software may be
used under the terms of a subsequent version, You may also choose to use that version.

4.3. Modified Versions

If You create or use a modified version of this License (new, modified, or different terms
or conditions), You must remove the notice in Exhibit A and apply your modified license.
You may not use the terms of this License or any open source license managed by the Mozilla
Foundation to endorse or promote products derived from your modified License.

5. Disclaimer of Representations and Warranties

COVERED SOFTWARE IS PROVIDED UNDER THIS LICENSE ON AN “AS IS” BASIS, WITHOUT WARRANTY OF
ANY KIND, EITHER EXPRESSED, IMPLIED, OR STATUTORY, INCLUDING, WITHOUT LIMITATION, WARRANTIES
THAT THE COVERED SOFTWARE IS FREE OF DEFECTS, MERCHANTABLE, FIT FOR A PARTICULAR PURPOSE
OR NON-INFRINGING. THE ENTIRE RISK AS TO THE QUALITY AND PERFORMANCE OF THE COVERED SOFTWARE
IS WITH YOU. SHOULD ANY COVERED SOFTWARE PROVE DEFECTIVE IN ANY RESPECT, YOU (NOT THE INITIAL
DEVELOPER OR ANY OTHER CONTRIBUTOR) ASSUME THE COST OF ANY NECESSARY SERVICING, REPAIR OR
CORRECTION. THIS DISCLAIMER OF WARRANTY CONSTITUTES AN ESSENTIAL PART OF THIS LICENSE. NO USE
OF ANY COVERED SOFTWARE IS AUTHORIZED HEREUNDER EXCEPT UNDER THIS DISCLAIMER.

6. Limitation of Liability

UNDER NO CIRCUMSTANCES AND UNDER NO LEGAL THEORY, WHETHER TORT (INCLUDING NEGLIGENCE),
CONTRACT, OR OTHERWISE, SHALL ANY CONTRIBUTOR, OR THE INITIAL DEVELOPER, BE LIABLE TO YOU
FOR ANY DIRECT, INDIRECT, SPECIAL, INCIDENTAL, OR CONSEQUENTIAL DAMAGES OF ANY CHARACTER
INCLUDING, WITHOUT LIMITATION, DAMAGES FOR LOST PROFITS, LOSS OF GOODWILL, WORK STOPPAGE,
COMPUTER FAILURE OR MALFUNCTION, OR ANY AND ALL OTHER COMMERCIAL DAMAGES OR LOSSES, EVEN IF
SUCH CONTRIBUTOR OR INITIAL DEVELOPER HAS BEEN ADVISED OF THE POSSIBILITY OF SUCH DAMAGES.
THIS LIMITATION OF LIABILITY SHALL NOT APPLY TO LIABILITY FOR DEATH OR PERSONAL INJURY
RESULTING FROM NEGLIGENCE TO THE EXTENT APPLICABLE LAW PROHIBITS SUCH LIMITATION. SOME
JURISDICTIONS DO NOT ALLOW THE EXCLUSION OR LIMITATION OF INCIDENTAL OR CONSEQUENTIAL DAMAGES,
SO THIS EXCLUSION AND LIMITATION MAY NOT APPLY TO YOU.

7. U.S. Government End Users

If the Covered Software is supplied to the U.S. Government, and is subject to the Mozilla
Public License, and is in whole or in part an item of “commercial computer software” as that
term is defined in 48 C.F.R. § 2.101 (October 1995) and 48 C.F.R. § 252.227-7014 (a)(1) (June
1995), then the Government’s rights with respect to the Covered Software will be only those
rights specified in this License. This Section 7 applies to all Covered Software regardless
of whether it has been modified.

8. Miscellaneous

This License represents the complete agreement concerning the subject matter hereof. If any
provision of this License is held to be unenforceable, such provision shall be reformed only
to the extent necessary to make it enforceable. Any law or regulation that provides that the
language of a contract shall be construed against the drafter shall not apply to this License.

9. Termination

9.1. For Cause

If You violate any term of this License in a material respect, and fail to cure such violation
within 30 days of becoming aware of the violation, this License and all of Your rights under
this License shall terminate immediately.

9.2. Effect of Termination

If You cease all distribution of Covered Software that is covered by this License, then Your
License from a particular Contributor terminates, but this does not affect the License of any
other Contributor. All of Your rights under this License terminate if You fail to cure a material
violation of this License and cease all distribution of Covered Software. Any sublicense provisions
that survive termination are not affected by this paragraph.

10. Contact Information

Mozilla Public License 2.0 is a free, open source software license. You can learn more about it
at https://www.mozilla.org/MPL/2.0/.

Exhibit A - Source Code License Notice

This Source Code Form is subject to the terms of the Mozilla Public License, v. 2.0. If a copy of
the MPL was not distributed with this file, You can obtain one at
http://mozilla.org/MPL/2.0/.

If it is not possible or desirable to include the notice in a particular file, then You may use the
short form of the notice:

This Source Code Form is subject to the terms of the Mozilla Public License, v. 2.0. If a copy of
the MPL was not distributed with this file, You can obtain one at http://mozilla.org/MPL/2.0/.
'''
};
